# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-07 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0037_import_optin_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditalert',
            name='admins',
            field=models.ManyToManyField(help_text='Administrators who will be alerted', related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
