# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_org_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='If this organization is custom', verbose_name='Custom'),
        ),
    ]
