# Generated by Django 2.2.4 on 2020-05-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0059_usersettings_authy_id"), ("orgs", "0059_creditalert_admin_emails")]

    operations = []
