# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_devicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='org',
        ),
    ]
