# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_devicetoken_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_token',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
