# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181122_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_token',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
