# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20171030_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='embedded_data',
            field=models.TextField(help_text='Extra data about this campaign event', null=True, verbose_name='Embedded Data'),
        ),
    ]
