# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 14:50
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_campaignevent_embedded_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='message',
            field=temba.utils.models.TranslatableField(max_length=2000, null=True),
        ),
    ]
