# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-23 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0113_msg_read_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=temba.utils.models.URLTextField(), help_text='The media attachments on this message if any', null=True, size=None),
        ),
    ]
