# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 14:50
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0114_auto_20190723_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=temba.utils.models.TranslatableField(help_text='The localized versions of the message text', max_length=2000, verbose_name='Translations'),
        ),
    ]
