# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0111_auto_20170824_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='flow_type',
            field=models.CharField(choices=[('F', 'Message flow'), ('M', 'Single Message Flow'), ('V', 'Phone call flow'), ('S', 'Android Survey'), ('Y', 'Simple Survey'), ('U', 'USSD flow')], default='F', help_text='The type of this flow', max_length=1),
        ),
    ]
