# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0037_import_optin_flow'),
        ('contacts', '0072_contact_salesforce_id'),
        ('flows', '0130_auto_20180223_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('path', models.CharField(help_text='Path to image', max_length=255)),
                ('exif', models.TextField(blank=True, help_text='A JSON representation the exif', null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_images', to='contacts.Contact')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='flows_flowimage_creations', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_images', to='flows.Flow')),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='flows_flowimage_modifications', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='flow_images', to='orgs.Org')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
