# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0132_auto_20181107_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowimage',
            name='name',
            field=models.CharField(default=' ', help_text='Image name', max_length=255),
            preserve_default=False,
        ),
    ]
