# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0132_exportflowimagestask'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportflowimagestask',
            name='file_downloaded',
            field=models.NullBooleanField(default=False, help_text='If the file was downloaded'),
        ),
        migrations.AddField(
            model_name='exportflowimagestask',
            name='file_path',
            field=models.CharField(help_text='Path to downloadable file', max_length=255, null=True),
        ),
    ]
