# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0133_auto_20190225_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportflowimagestask',
            name='cleaned',
            field=models.NullBooleanField(default=False, help_text='If the file was removed after downloaded'),
        ),
    ]
