# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0134_exportflowimagestask_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowimage',
            name='path_thumbnail',
            field=models.CharField(help_text='Image thumbnail URL', max_length=255, null=True),
        ),
    ]
