# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0135_flowimage_path_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrun',
            name='embedded_fields',
            field=models.TextField(blank=True, help_text='A JSON representation of any embedded flow fields the user has added', null=True),
        ),
    ]
