# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0136_flowrun_embedded_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstart',
            name='embedded_data',
            field=models.TextField(help_text='Embedded data passed to the flow start (json)', null=True),
        ),
    ]
