# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-03 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0136_auto_20190401_1225'),
        ('flows', '0133_auto_20190205_1118'),
    ]

    operations = [
    ]
