# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-19 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0139_populate_launch_status_for_surveyor_flows'),
        ('flows', '0137_flowstart_embedded_data'),
    ]

    operations = [
    ]
