# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-25 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0140_merge_20190719_0119'),
        ('flows', '0140_merge_20190723_1038'),
    ]

    operations = [
    ]
