# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0140_merge_20190723_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstep',
            name='rule_value_corrected',
            field=models.TextField(help_text='The value corrected that was matched in our category for this ruleset, null on ActionSets', null=True),
        ),
    ]
