# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-21 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0141_merge_20190725_1547'),
        ('flows', '0141_flowstep_rule_value_corrected'),
    ]

    operations = [
    ]
