# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0067_auto_20170808_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='invited_on',
            field=models.DateTimeField(blank=True, editable=False, help_text='When this item was originally invited', null=True),
        ),
    ]
