# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0068_contact_invited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='invitation_status',
            field=models.CharField(choices=[('S', 'Sent'), ('A', 'Accepted'), ('R', 'Rejected')], help_text='The invitation status of this contact', max_length=1, null=True),
        ),
    ]
