# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 02:53
from __future__ import unicode_literals

from django.db import migrations, models


def populate_contact_field_invitation_order(apps, schema_editor):
    Contacts = apps.get_model('contacts', 'Contact')

    all_contacts = Contacts.objects.all().exclude(invited_on__isnull=True)
    print("Fetched %d contacts to set invitation order" % len(all_contacts))

    num_updated = 0

    for contact in all_contacts:
        invitation_order = 0
        if contact.invitation_status == 'S':
            invitation_order = 1
        elif contact.invitation_status == 'A':
            invitation_order = 2
        elif contact.invitation_status == 'R':
            invitation_order = 3

        contact.invitation_order = invitation_order
        contact.save(update_fields=['invitation_order'])

        num_updated += 1

        if num_updated % 1000 == 0:
            print(" > Updated %d of %d contacts" % (num_updated, len(all_contacts)))


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0069_contact_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='invitation_order',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Order', null=True),
        ),
        migrations.RunPython(populate_contact_field_invitation_order)
    ]
