# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0070_contact_invitation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='invitation_order',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='invitation_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='invited_on',
        ),
    ]
