# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0071_auto_20180405_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='freshchat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Freshchat ID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='in_live_chat',
            field=models.BooleanField(default=False, help_text='Whether this contact is in live chat with a human agent', verbose_name='In Live Chat'),
        ),
    ]
