# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import temba.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0070_contact_invitation_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0036_ensure_anon_user_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('uuid', models.CharField(db_index=True, default=temba.utils.models.generate_uuid, help_text='The unique identifier for this object', max_length=36, unique=True, verbose_name='Unique Identifier')),
                ('name', models.CharField(help_text='The name for this trackable link', max_length=64)),
                ('slug', models.SlugField(help_text='The trackable link slug', max_length=64)),
                ('shorten_url', models.URLField(help_text='The trackable link slug', max_length=100)),
                ('destination', models.URLField(help_text='The destination URL for this trackable link', max_length=255)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this trackable link is archived')),
                ('clicks_count', models.PositiveIntegerField(default=0, help_text='Clicks count for this trackable link')),
                ('contacts', models.ManyToManyField(help_text='The users which clicked on this link', related_name='contact_links', to='contacts.Contact')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='links_link_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='links_link_modifications', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='orgs.Org')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
