# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0070_contact_invitation_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_remove_link_shorten_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('contact', models.ForeignKey(help_text='The users which clicked on this link', on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='contacts.Contact')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='links_linkcontacts_creations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='link',
            name='contacts',
        ),
        migrations.AddField(
            model_name='linkcontacts',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='links.Link'),
        ),
        migrations.AddField(
            model_name='linkcontacts',
            name='modified_by',
            field=models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='links_linkcontacts_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
