# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180118_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='slug',
        ),
    ]
