# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0010_auto_20170509_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='embedded_data',
            field=models.TextField(help_text='Extra data about this trigger', null=True, verbose_name='Embedded Data'),
        ),
    ]
