name: Stale Manual

on:
  workflow_dispatch:
    inputs:
      operations:
        description: 'Number of operations'
        default: "300"
        required: true

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: ${{ github.event.inputs.operations }}
        stale-issue-label: 'inactive'
        stale-issue-message: 'Without activity, this issue will be closed in 14 days.'
        close-issue-message: 'This issue was closed for inactivity.'
        stale-pr-message: 'Without activity, this PR will be closed in 14 days.'
        close-pr-message: 'This PR was closed for inactivity.'
        stale-pr-label: 'inactive'
        days-before-pr-stale: 30
        days-before-pr-close: 14
        days-before-issue-stale: 30
        days-before-issue-close: 14
